### ISSUE TITLE
Nie działa Apple Pay

### ISSUE THREAD

**Issue by oflospzoo** [PayU-EMEA/plugin_magento#75]
Przy próbie zapłaty za pomocą Apple Pay nie udaje się przekierowanie do PayU.
Na stronie https://www.mojadomena.pl/checkout/onepage/failure/ pojawia sie błąd:
"There was a problem with the payment initialization, please contact system administrator."
W logach jest: "ERROR_VALUE_INVALID - OPENPAYU_PAYMENT_CREATE_INCORRECT_CHECKOUT_PAY_METHOD".

Dane są poprawne, jest forma płatności "jp", tak jak w dokumentacji API:
array('payMethod' => array('type' => 'PBL', 'value' => 'jp')).

**Comment by lgrzesiak** [comment]
Aby ją wywołać, nie wystarczy podanie samej metody, ale również dodatkowego parametru.
Proszę zapoznać się z dokumentacją nt. tej metody płatności: http://developers.payu.com/pl/apple_pay.html
